import type { Metadata } from "next";
import '@/app/globals.css'
import Navbar from "@/components/layout/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import SessionProvider from "@/lib/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className="font-brico"
      >
        <SessionProvider session={session}>
          <Navbar/>
                  {children}
                </SessionProvider>
        
      </body>
    </html>
  );
}
